[package]
edition = "2021"
name = "jsonish"
version.workspace = true
authors.workspace = true
description.workspace = true

license-file.workspace = true

[lints.rust]
dead_code = "allow"
elided_named_lifetimes = "deny"
unused_imports = "allow"
unused_variables = "allow"

[dependencies]
anyhow.workspace = true
baml-types = { path = "../baml-types" }
bstd.workspace = true
colored = "2"
pest = "2.1.3"
indoc.workspace = true
internal-baml-jinja = { path = "../jinja-runtime" }
internal-baml-core = { path = "../baml-core" }
log = "0.4.20"
indexmap = "2.1.0"
strsim = "0.10.0"
serde_json.workspace = true
serde.workspace = true
# jsonschema = "0.17.1"
either = "1.10.0"
test-log = "0.2.16"
regex.workspace = true

[dev-dependencies]
assert-json-diff = "2.0.2"
